# Generated by Django 5.0.2 on 2024-07-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_alter_albummodel_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albummodel',
            old_name='name',
            new_name='Album_name',
        ),
    ]
